#Use the official nginx base image
FROM nginx:latest

#Copy your custom index.html file into the container
COPY  index.html /ussr/share/nginx/html/index.html

#(Optional) Expose port 80 if you haven't already
EXPOSE 80
#(Optional) 